FORMAT: 1A

# XingInterview
This API is a data source for a XING interview. Enjoy :)

# Group Jobs
Jobs related resources of the **Jobs API**

## Jobs Collection [/jobs]
### List all Jobs [GET]
+ Response 200 (application/json)

        [
            {
                "id": 1,
                "title": "iOS Engineer at XING",
                "job_type": "FULL_TIME",
                "created_at": "2014-11-17T10:57:46Z",
                "logo_url": "https://www.xing.com/img/custom/cp/assets/logo/2/6/8/616/logo/xing_web_72dpi_ohne_claim_gro%C3%9F.jpg"
            },
            {
                "id": 2,
                "title": "iOS Entwickler in der wünderschönen Stadt Hamburg bei XING",
                "job_type": "FULL_TIME",
                "created_at": "2014-11-17T14:57:46Z",
                "logo_url": "https://www.xing.com/img/custom/cp/assets/logo/2/6/8/616/logo/xing_web_72dpi_ohne_claim_groß.jpg"
            },
            {
                "id": 3,
                "title": "Some other job",
                "job_type": "PART_TIME",
                "created_at": "2014-10-17T14:57:46Z",
                "logo_url": "https://www.xing.com/img/custom/cp/assets/logo/2/b/6/694/logo/XingEvents_Logo_285x56.jpg"
            },
            {
                "id": 4,
                "title": "You will learn here a lot!",
                "job_type": "STUDENT",
                "created_at": "2014-11-05T14:57:46Z",
                "logo_url": "https://www.xing.com/img/custom/cp/assets/logo/1/7/3/371/logo/kununu_xingcomp_blue_service.jpg"
            },
            {
                "id": 5,
                "title": "Nice job position in sunny Barcelona",
                "job_type": "FULL_TIME",
                "created_at": "2013-11-17T14:57:46Z",
                "logo_url": "https://www.xing.com/img/custom/cp/assets/logo/2/6/8/616/logo/xing_web_72dpi_ohne_claim_groß.jpg"
            },
            {
                "id": 6,
                "title": "It's rainy here but nice - Hamburg",
                "job_type": "PART_TIME",
                "created_at": "2014-11-13T14:57:46Z",
                "logo_url": "https://www.xing.com/img/custom/cp/assets/logo/2/6/8/616/logo/xing_web_72dpi_ohne_claim_groß.jpg"
            },
            {
                "id": 7,
                "title": "I like long titles, I like long titles, I like long titles",
                "job_type": "STUDENT",
                "created_at": "2014-11-16T14:57:46Z",
                "logo_url": "https://www.xing.com/img/custom/cp/assets/logo/1/7/3/371/logo/kununu_xingcomp_blue_service.jpg"
            },
            {
                "id": 8,
                "title": "The last one",
                "job_type": "FULL_TIME",
                "created_at": "2012-08-17T14:57:46Z",
                "logo_url": "https://www.xing.com/img/custom/cp/assets/logo/2/6/8/616/logo/xing_web_72dpi_ohne_claim_groß.jpg"
            }
        ]
